var leaderboardData = {
    Asia: [
        { Team: "Payoneer", SDR: "Maryam Rehman", Appointments: 33 },
        { Team: "Payoneer", SDR: "Mehwish Ali", Appointments: 28 },
        { Team: "PureVPN & PureDome", SDR: "Amar", Appointments: 10 },
        { Team: "PureVPN & PureDome", SDR: "Sophia", Appointments: 10 },
        { Team: "Payoneer Checkout", SDR: "Ali Hassan", Appointments: 5 },
    ],
    EMEA: [
        { Team: "Pureversity", SDR: "Zuhaib", Appointments: 14 },
        { Team: "ABCL", SDR: "Usman Hussain", Appointments: 8 },
        { Team: "Pureversity", SDR: "Babar", Appointments: 7 },
        { Team: "Qubriux", SDR: "Anas", Appointments: 5 },
        { Team: "ABCL", SDR: "Iqra Irshad", Appointments: 2 },
        { Team: "ABCL", SDR: "Muhammad Asim", Appointments: 1 },
    ],
    "US, UK & Canada": [
        { Team: "illumin", SDR: "Hammad Faisal", Appointments: 10 },
        { Team: "Avibra", SDR: "Earnest Isic", Appointments: 8 },
        { Team: "Payactiv", SDR: "Samuel Bhatti", Appointments: 8 },
        { Team: "Payactiv", SDR: "Nikolai Noronha", Appointments: 7 },
        { Team: "Payactiv", SDR: "Usman Amin", Appointments: 7 },
        { Team: "FP&A", SDR: "Haseeb", Appointments: 6 },
        { Team: "illumin", SDR: "Ali Murtaza", Appointments: 6 },
        { Team: "Payactiv", SDR: "Anthony Dsouza", Appointments: 6 },
        { Team: "Payactiv", SDR: "Shahmir Shah", Appointments: 6 },
        { Team: "CanopyConnect", SDR: "Ibrahim Shahid", Appointments: 5 },
        { Team: "Payactiv", SDR: "Ali Saqlain", Appointments: 5 },
        { Team: "CanopyConnect", SDR: "Vivek kumar", Appointments: 4 },
        { Team: "Payactiv", SDR: "Moiz Sheraz", Appointments: 4 },
        { Team: "Payactiv", SDR: "Shahwaiz Alam", Appointments: 4 },
        { Team: "Payactiv", SDR: "Shiraz Iqbal", Appointments: 4 },
        { Team: "Payactiv", SDR: "Tahir Yaqoob", Appointments: 4 },
        { Team: "NINJIO", SDR: "Joshua Rodrigues", Appointments: 4 },
        { Team: "illumin", SDR: "Amjad Baig", Appointments: 3 },
        { Team: "illumin", SDR: "Khuzaima Tahir", Appointments: 3 },
        { Team: "Payactiv", SDR: "Shane Samson", Appointments: 3 },
        { Team: "NINJIO", SDR: "Muneeb Khan", Appointments: 3 },
        { Team: "NINJIO", SDR: "Omer Abdali", Appointments: 3 },
        { Team: "CanopyConnect", SDR: "Daniyal Babar", Appointments: 2 },
        { Team: "illumin", SDR: "Ahmed Ali", Appointments: 2 },
        { Team: "Payactiv", SDR: "Ahmed Sarwaich", Appointments: 2 },
        { Team: "Payactiv", SDR: "Matthew Noor", Appointments: 2 },
        { Team: "Avibra", SDR: "Jayden Correa", Appointments: 1 },
        { Team: "FP&A", SDR: "Sunny", Appointments: 1 },
        { Team: "CanopyConnect", SDR: "Gareth Cajetan", Appointments: 1 },
        { Team: "CanopyConnect", SDR: "Webster Davies", Appointments: 1 },
        { Team: "Payactiv", SDR: "Jaish Yousaf", Appointments: 1 },
        { Team: "Payactiv", SDR: "Muhammad Wajahat", Appointments: 1 },
        { Team: "Qubriux", SDR: "Samuel", Appointments: 1 },
    ]

};

var showupLeaderboardData = {
    Asia: [
        { Team: "Payoneer", SDR: "Mehwish Ali", Showups: 24 },
        { Team: "Payoneer", SDR: "Maryam Rehman", Showups: 23 },
        { Team: "PureVPN & PureDome", SDR: "Sophia", Showups: 7 },
        { Team: "PureVPN & PureDome", SDR: "Amar", Showups: 4 },
        { Team: "Payoneer Checkout", SDR: "Ali Hassan", Showups: 2 },
    ],
    EMEA: [
        { Team: "Pureversity", SDR: "Zuhaib", Showups: 10 },
        { Team: "ABCL", SDR: "Usman Hussain", Showups: 7 },
        { Team: "ABCL", SDR: "Muhammad Asim", Showups: 3 },
        { Team: "Pureversity", SDR: "Babar", Showups: 3 },
        { Team: "ABCL", SDR: "Iqra Irshad", Showups: 2 },
        { Team: "Pureversity", SDR: "Kasim", Showups: 1 },
    ],
    "US, UK & Canada": [
        { Team: "illumin", SDR: "Hammad Faisal", Showups: 10 },
        { Team: "illumin", SDR: "Ali Murtaza", Showups: 7 },
        { Team: "Payactiv", SDR: "Usman Amin", Showups: 6 },
        { Team: "Payactiv", SDR: "Anthony Dsouza", Showups: 5 },
        { Team: "Payactiv", SDR: "Samuel Bhatti", Showups: 5 },
        { Team: "NINJIO", SDR: "Joshua Rodrigues", Showups: 5 },
        { Team: "Avibra", SDR: "Earnest Isic", Showups: 4 },
        { Team: "Payactiv", SDR: "Shahmir Shah", Showups: 4 },
        { Team: "Payactiv", SDR: "Shiraz Iqbal", Showups: 4 },
        { Team: "Canopy", SDR: "Ibrahim Shahid", Showups: 3 },
        { Team: "illumin", SDR: "Khuzaima Tahir", Showups: 3 },
        { Team: "Payactiv", SDR: "Shahwaiz Alam", Showups: 3 },
        { Team: "Payactiv", SDR: "Shane Samson", Showups: 3 },
        { Team: "NINJIO", SDR: "Muneeb Khan", Showups: 3 },
        { Team: "NINJIO", SDR: "Omer Abdali", Showups: 3 },
        { Team: "Canopy", SDR: "Daniyal Babar", Showups: 2 },
        { Team: "Canopy", SDR: "Vivek kumar", Showups: 2 },
        { Team: "illumin", SDR: "Ahmed Ali", Showups: 2 },
        { Team: "illumin", SDR: "Amjad Baig", Showups: 2 },
        { Team: "Payactiv", SDR: "Ali Saqlain", Showups: 2 },
        { Team: "Payactiv", SDR: "Nikolai Noronha", Showups: 2 },
        { Team: "Payactiv", SDR: "Tahir Yaqoob", Showups: 2 },
        { Team: "FP&A", SDR: "Haseeb", Showups: 1 },
        { Team: "FP&A", SDR: "Yaseen", Showups: 1 },
        { Team: "Canopy", SDR: "Gareth Cajetan", Showups: 1 },
        { Team: "Payactiv", SDR: "Ahmed Sarwaich", Showups: 1 },
        { Team: "Payactiv", SDR: "Matthew Noor", Showups: 1 },
        { Team: "Payactiv", SDR: "Muhammad Wajahat", Showups: 1 },
        { Team: "Qubriux", SDR: "Samuel", Showups: 1 },
    ]
};
